#BEGIN_PROPERTIES#
{
    "version": "1.2",
    "commandsIntroduced": ["map.getAdjacentEmptyCells"],
    "music": "Searching"
}
#END_PROPERTIES#
/*
 * robotMaze.js
 *
 * Синий ключ спрятан в лабиринте, и достать его
 * будет непросто.
 *
 * Хорошо, что вы специалист по ИИ, — иначе мы
 * ушли бы отсюда с пустыми руками.
 */

function startLevel(map) {
#START_OF_START_LEVEL#
    // Подсказка: клавишами R или 5 можно «переждать» ход,
    // не двигая игрока, пока робот перемещается.

    map.getRandomInt = function(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    map.placePlayer(map.getWidth()-1, map.getHeight()-1);
    var player = map.getPlayer();

    map.defineObject('robot', {
        'type': 'dynamic',
        'symbol': 'R',
        'color': 'gray',
        'onCollision': function (player, me) {
            me.giveItemTo(player, 'blueKey');
        },
        'behavior': function (me) {
#BEGIN_EDITABLE#
            // ходим случайно
            var moves = map.getAdjacentEmptyCells(me.getX(), me.getY());
            // getAdjacentEmptyCells даёт массив пар ((x, y), направление)
            me.move(moves[map.getRandomInt(0, moves.length - 1)][1]);













































#END_EDITABLE#
        }
    });

    map.defineObject('barrier', {
        'symbol': '░',
        'color': 'purple',
        'impassable': true,
        'passableFor': ['robot']
    });

    map.placeObject(0, map.getHeight() - 1, 'exit');
    map.placeObject(1, 1, 'robot');
    map.placeObject(map.getWidth() - 2, 8, 'blueKey');
    map.placeObject(map.getWidth() - 2, 9, 'barrier');

    var autoGeneratedMaze = new ROT.Map.DividedMaze(map.getWidth(), 10);
    autoGeneratedMaze.create( function (x, y, mapValue) {
        // не рисуем лабиринт поверх робота и барьера
        if ((x == 1 && y == 1) || (x == map.getWidth() - 2 && y >= 8)) {
            return 0;
        } else if (mapValue === 1) { //0 — пустое место, 1 — стена
            map.placeObject(x,y, 'block');
        } else {
            map.placeObject(x,y,'empty');
        }
    });
#END_OF_START_LEVEL#
}

function validateLevel(map) {
    map.validateExactlyXManyObjects(1, 'exit');
    map.validateExactlyXManyObjects(1, 'robot');
    map.validateAtMostXObjects(1, 'blueKey');
}

function onExit(map) {
    if (!map.getPlayer().hasItem('blueKey')) {
        map.writeStatus("Нам нужно достать этот ключ!");
        return false;
    } else {
        return true;
    }
}
